# Generated by Django 4.1.1 on 2022-10-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2B_App', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auction_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_date',
            field=models.TextField(null=True),
        ),
    ]
