# Generated by Django 4.1.1 on 2022-10-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2B_App', '0007_remove_auction_user_auction_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
