# Generated by Django 4.0.3 on 2022-10-18 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('B2B_App', '0009_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='B2B_App.categ'),
        ),
    ]
