# Generated by Django 4.0.3 on 2022-10-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2B_App', '0012_alter_product_farmer_alter_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catg',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
