# Generated by Django 4.0.3 on 2022-10-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2B_App', '0013_rename_catg_product_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
