# Generated by Django 4.0.3 on 2022-10-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2B_App', '0014_alter_product_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
