# Generated by Django 4.0.3 on 2022-10-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B2B_App', '0016_remove_product_user_alter_product_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
    ]
