# Generated by Django 4.0.3 on 2022-10-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B2B_App', '0019_product_farmer_alter_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categ',
        ),
    ]
