# Generated by Django 4.0.3 on 2022-10-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2B_App', '0025_fixed_auction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixed_auction',
            name='Auction_price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
