# Generated by Django 3.2 on 2022-10-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2B_App', '0027_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='reply',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
