# Generated by Django 4.0.3 on 2022-11-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2B_App', '0028_chat_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixed_auction',
            name='com_date',
            field=models.DateField(auto_now=True),
        ),
    ]
