# Generated by Django 4.1.7 on 2023-03-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2B_App', '0029_fixed_auction_com_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='admin_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
